name: trans_tim
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lottie: ^2.7.0
  get_storage: ^2.1.1
  geolocator: ^10.1.0
  url_launcher: ^6.2.1
  geocoding: ^2.1.1
  uuid: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.14.10+1
  flutter_credit_card: ^4.0.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "asset/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - asset/